version: '3.8'

services:
  php:
    image: php:fpm
    volumes:
      - ./html/public:/var/www/html/public
    networks:
      - my_network
  
  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./html/public:/var/www/html/public
    depends_on:
      - php
    networks:
      - my_network

networks:
  my_network:
